//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportClub.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить исполнителя.
        /// </summary>
        public static string AddArt {
            get {
                return ResourceManager.GetString("AddArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был добавлен исполнитель:  .
        /// </summary>
        public static string AddedArtist {
            get {
                return ResourceManager.GetString("AddedArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Была добавлена песня:  .
        /// </summary>
        public static string AddedSong {
            get {
                return ResourceManager.GetString("AddedSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был добавлен жанр:  .
        /// </summary>
        public static string AddedStyle {
            get {
                return ResourceManager.GetString("AddedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление.
        /// </summary>
        public static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить песню.
        /// </summary>
        public static string AddSong {
            get {
                return ResourceManager.GetString("AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *введите возраст.
        /// </summary>
        public static string AgeRequired {
            get {
                return ResourceManager.GetString("AgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все песни.
        /// </summary>
        public static string AllSongs {
            get {
                return ResourceManager.GetString("AllSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to исполнителям.
        /// </summary>
        public static string ArtSort {
            get {
                return ResourceManager.GetString("ArtSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить уровень доступа.
        /// </summary>
        public static string Changelevel {
            get {
                return ResourceManager.GetString("Changelevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвердите удаление.
        /// </summary>
        public static string Confirmdeletion {
            get {
                return ResourceManager.GetString("Confirmdeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвержденные пользователи.
        /// </summary>
        public static string Confirmdusers {
            get {
                return ResourceManager.GetString("Confirmdusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить регистрацию.
        /// </summary>
        public static string Confirmregistration {
            get {
                return ResourceManager.GetString("Confirmregistration", resourceCulture);
            }
        }
        public static string DateB
        {
            get
            {
                return ResourceManager.GetString("DateB", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить исполнителя.
        /// </summary>
        public static string DeleteArt {
            get {
                return ResourceManager.GetString("DeleteArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель был удален:  .
        /// </summary>
        public static string DeletedArtist {
            get {
                return ResourceManager.GetString("DeletedArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был удален жанр:  .
        /// </summary>
        public static string DeletedStyle {
            get {
                return ResourceManager.GetString("DeletedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Была удалена песня:  .
        /// </summary>
        public static string DelSong {
            get {
                return ResourceManager.GetString("DelSong", resourceCulture);
            }
        }
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        public static string Dopname
        {
            get
            {
                return ResourceManager.GetString("Dopname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отредактирован исполнитель: .
        /// </summary>
        public static string EdArtist {
            get {
                return ResourceManager.GetString("EdArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать исполнителя.
        /// </summary>
        public static string EditArt {
            get {
                return ResourceManager.GetString("EditArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование песни.
        /// </summary>
        public static string EditSong {
            get {
                return ResourceManager.GetString("EditSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отредактирована песня:  .
        /// </summary>
        public static string EdSong {
            get {
                return ResourceManager.GetString("EdSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отредактирован жанр:  .
        /// </summary>
        public static string EdStyle {
            get {
                return ResourceManager.GetString("EdStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта .
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *почта обязательное поле.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *почта уже зарегестрирована.
        /// </summary>
        public static string emailused {
            get {
                return ResourceManager.GetString("emailused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string enterArt {
            get {
                return ResourceManager.GetString("enterArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название.
        /// </summary>
        public static string enterName {
            get {
                return ResourceManager.GetString("enterName", resourceCulture);
            }
        }
        public static string female
        {
            get
            {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to *заполните все поля.
        /// </summary>
        public static string fields {
            get {
                return ResourceManager.GetString("fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать.
        /// </summary>
        public static string Filtr {
            get {
                return ResourceManager.GetString("Filtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать по:.
        /// </summary>
        public static string FiltrBy {
            get {
                return ResourceManager.GetString("FiltrBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        public static string gender
        {
            get
            {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень доступа.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to более 8 симолов, как минимум одна цифра, одна(A-Z), одна(a-z), один специальный символ.
        /// </summary>
        public static string LightPass {
            get {
                return ResourceManager.GetString("LightPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите испонителя из списка.
        /// </summary>
        public static string Listofartists {
            get {
                return ResourceManager.GetString("Listofartists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите жанр из списка.
        /// </summary>
        public static string Listofstyles {
            get {
                return ResourceManager.GetString("Listofstyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to логин.
        /// </summary>
        public static string loginN {
            get {
                return ResourceManager.GetString("loginN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to логин/пароль не верный.
        /// </summary>
        public static string loginpassword {
            get {
                return ResourceManager.GetString("loginpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *логин уже зарегестрирован.
        /// </summary>
        public static string loginused {
            get {
                return ResourceManager.GetString("loginused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *логин обязательное поле.
        /// </summary>
        public static string LogRequired {
            get {
                return ResourceManager.GetString("LogRequired", resourceCulture);
            }
        }
        public static string man
        {
            get
            {
                return ResourceManager.GetString("man", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Музыкальный портал.
        /// </summary>
        public static string MusicPortal {
            get {
                return ResourceManager.GetString("MusicPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string nameArt {
            get {
                return ResourceManager.GetString("nameArt", resourceCulture);
            }
        }
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Новые пользователи.
        /// </summary>
        public static string Newusers {
            get {
                return ResourceManager.GetString("Newusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *подтверждение пароля обязательно.
        /// </summary>
        public static string PassConRequired {
            get {
                return ResourceManager.GetString("PassConRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *пароли не совпадают.
        /// </summary>
        public static string passnoteq {
            get {
                return ResourceManager.GetString("passnoteq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *пароль обязательное поле.
        /// </summary>
        public static string PassRequired {
            get {
                return ResourceManager.GetString("PassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтвердите пароль.
        /// </summary>
        public static string passwordConf {
            get {
                return ResourceManager.GetString("passwordConf", resourceCulture);
            }
        }
        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Загрузите фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        public static string Post
        {
            get
            {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Зарегестрироваться.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        public static string Required
        {
            get
            {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Название песни.
        /// </summary>
        public static string Songname {
            get {
                return ResourceManager.GetString("Songname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать пo:.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        public static string Speciality
        {
            get
            {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to жанрам.
        /// </summary>
        public static string StyleSort {
            get {
                return ResourceManager.GetString("StyleSort", resourceCulture);
            }
        }
        public static string Surname
        {
            get
            {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *некорректный возраст.
        /// </summary>
        public static string unage {
            get {
                return ResourceManager.GetString("unage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *некорректная почта.
        /// </summary>
        public static string unemail {
            get {
                return ResourceManager.GetString("unemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *неверный логин или пароль.
        /// </summary>
        public static string unlogpass {
            get {
                return ResourceManager.GetString("unlogpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пользователь.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ожидание регистрации.
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to году выхода.
        /// </summary>
        public static string YearSort {
            get {
                return ResourceManager.GetString("YearSort", resourceCulture);
            }
        }
    }
}
